<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216121538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT fk_161498d371f7e88b');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT fk_161498d399e6f5df');
        $this->addSql('DROP INDEX uniq_event_reference');
        $this->addSql('ALTER TABLE card ALTER event_id DROP NOT NULL');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D399E6F5DF FOREIGN KEY (player_id) REFERENCES player (id)');
        $this->addSql('DROP INDEX idx_70f2bd0fe48fd9053ed13fc');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT fk_232b318c71f7e88b');
        $this->addSql('DROP INDEX idx_232b318c71f7e88b462ce4f5');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE winner DROP CONSTRAINT fk_cf6600e4acc9a20');
        $this->addSql('ALTER TABLE winner ADD CONSTRAINT FK_CF6600E4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D371F7E88B');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D399E6F5DF');
        $this->addSql('ALTER TABLE card ALTER event_id SET NOT NULL');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT fk_161498d371f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT fk_161498d399e6f5df FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_reference ON card (event_id, reference)');
        $this->addSql('CREATE INDEX idx_70f2bd0fe48fd9053ed13fc ON draw (game_id, order_index)');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C71F7E88B');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT fk_232b318c71f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_232b318c71f7e88b462ce4f5 ON game (event_id, "position")');
        $this->addSql('ALTER TABLE winner DROP CONSTRAINT FK_CF6600E4ACC9A20');
        $this->addSql('ALTER TABLE winner ADD CONSTRAINT fk_cf6600e4acc9a20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
